### PR TITLE
Add Russian translation

### PR DESCRIPTION
**Pull request by bekreyev**

### CODE REVIEW

**Comment by giggls** [comment]
Hm I tried to activate this version on https://camping.openstreetmap.de/map-dev/
Does not seem to work.

**Comment by giggls** [comment]
OK, I updated the URL. Can you check again if the translation works as expected?

**Comment by bekreyev** [comment]
> OK, I updated the URL. Can you check again if the translation works as expected?

Please, update Russian flag? first version was wrong

**Comment by giggls** [comment]
Good now?

**Comment by bekreyev** [comment]
I think for a start it will be good for the Russian version.

**Comment by giggls** [comment]
OK, I will merge this then.

**Comment by giggls** [comment]
Did some minor improvements. Would you please have a look at https://github.com/giggls/opencampsitemap/blob/master/index.html.ru and https://github.com/giggls/opencampsitemap/blob/master/l10n/ru.js to add them?

**Pull request merged**
