### PR TITLE
Load and display reviews from Mangrove

### PR DESCRIPTION
**Pull request by wtimme**
With this branch, the reviews for a camp site are retrieved from Mangrove when the user selects a camp site on the map.

It still requires some testing (especially edge cases, such as multiple camp sites near each other, camp sites without any reviews), but the rough idea can already be seen.

Here's a screenshot of the feature in action:

Screenshot 2022-08-03 at 13 24 18

### CODE REVIEW

**Comment by giggls** [comment]
Merged this into dev-site running at https://camping.openstreetmap.de/map-dev/
Feel free to contact me if you want a shell-account.
This will definitely need some testing before going live to avoid problems a I had with the initial mangrove support.
I will announce this in the discussion about the review feature.

**Comment by giggls** [comment]
Made a feature branch "mangrove" which is now mirrored at https://camping.openstreetmap.de/map-dev/
This will allow me to work on it.

**Comment by giggls** [comment]
Showing the images posted on mangrove would be nice.
I just wrote a review which has one: 
https://camping.openstreetmap.de/map-dev/index.html.de#17/49.86074/10.91468/0/1/bef/way/164951603

**Comment by wtimme** [comment]
I have added the date and the author's name (if available) to the review:

Screenshot 2022-08-03 at 20 48 30

Is adding support for the images something that _must_ be part of this pull request, or could we move it to a "V2"?

**Comment by wtimme** [comment]
Sven, do you have a suggestion how to proceed with the large review button at the top?

By the way, due to a missing bracket in the CSS file, the elements were not styled at all. I fixed that with [f85ec0c](https://github.com/giggls/opencampsitemap/pull/27/commits/f85ec0ce5025925431b9f8922eb6aa1c7b259907).

**Comment by wtimme** [comment]
I've added attribution to the top of the review section, so that users immediately know where the reviews are coming from.

Screenshot 2022-08-03 at 22 13 24

**Comment by wtimme** [comment]
I've reworked the "Add review" button a bit and added it to the review section.

<table><tr><th>Without reviews</th><th>With reviews</th></tr><tr><td valign="top">Screenshot 2022-08-03 at 23 07 21</td><td>Screenshot 2022-08-03 at 23 07 34</td></tr></table>

Is there anything missing?

**Comment by giggls** [comment]
Merged this to my feature branch and enabled it on https://camping.openstreetmap.de/map-dev/
Two minor things: I would like to changed the light-blue background to the same color as the info-boxes with the osm description tag (did this on the link) and I wonder if we should move the reviews to the bottom of the sidebar using css.

**Comment by giggls** [comment]
> I have added the date and the author's name (if available) to the review:
> 
> Screenshot 2022-08-03 at 20 48 30
> 
> Is adding support for the images something that _must_ be part of this pull request, or could we move it to a "V2"?

This can certainly wait.

**Comment by giggls** [comment]
Got those:
```
diff --git a/campmap.css b/campmap.css
index a8c8a96..c5c5226 100644
--- a/campmap.css
+++ b/campmap.css
@@ -160,7 +160,7 @@ input:checked + .slider:before {
 
 #reviews_container h4 .powered_by {
   float: right;
-  color: lightgray;
+  color: gray;
 }
 
 #reviews_container ul {
@@ -169,7 +169,7 @@ input:checked + .slider:before {
 }
 
 #reviews_container .entry {
-  background-color: lightblue;
+  background-color: #ddddff;
   border-radius: 3px;
   padding: 4pt;
 }
@@ -185,7 +185,7 @@ input:checked + .slider:before {
 }
 
 #reviews_container .rating {
-  color: yellow;
+  color: #b8860b;
   display: inline;
   font-size: 14pt;
 }
```

**Comment by wtimme** [comment]
From your comment, I understood that you merely wanted for the background color to be changed. But sure, I'll update the other colors as well.

**Comment by giggls** [comment]
I also changed the star-colors because they where mostly invisible with the new background and the "powered by" because it was almost unreadable on my desktop screen.

**Comment by wtimme** [comment]
> I wonder if we should move the reviews to the bottom of the sidebar using css.

Personally, I find their current position to be quite fitting. In addition, I am not quite sure how that would look and feel, especially on small-screen devices. Is that something we could postpone to a later date, and merge this branch without it?

---

From my point of view, what is left to do is rigid testing of the feature. @jonsger and @lyxys, could you give us a hand here? We are looking for

- crowded places on the map with multiple camp sites in near vincity
- camp sites without reviews
- camp sites with reviews

Please give the feature a test ride on https://camping.openstreetmap.de/map-dev/ and report back if there's anything that needs to be addressed. Thanks in advance for your help!

**Comment by giggls** [comment]
Is there a way to find all reviewed sites on Mangrove?

Do you think we should add a sentence or two about Mangrove into "about" text?

**Comment by giggls** [comment]
OK, man findet einige, wenn man "camping" in die Suche eingibt.

**Comment by giggls** [comment]
This should also be a review here and not a description tag in OSM!
https://camping.openstreetmap.de/map-dev/#10/47.2503/14.6922/1/1/bef

**Comment by jonsger** [comment]
> Is there a way to find all reviewed sites on Mangrove?

https://api.mangrove.reviews/reviews gives you a CSV with all reviews (about 500)

**Comment by giggls** [comment]
Here are many sites located next to each other:
https://camping.openstreetmap.de/map-dev/#14/44.4218/-1.1681/1/1/bef

**Comment by wtimme** [comment]
The CSV that can be obtain via the endpoint you mentioned contains more than just camping sites. There are 489 entries, to be exact. Maybe we can get in touch with the Mangrove team and ask them for help. They have been pretty responsive on Matrix so far. In #12, @carabasiru mentioned that they were part of the Mangrove team. Maybe you can chime in?

As for the many sites next to each other: What worries me the most in these scenarios is that I am uncertain how well Mangrove resolves the coordinates to the reviews. It's bad for the trust of our users when they read reviews of one place which in reality were written for a different one. I'm not sure how that can be tested, though.

I like what Sven pointed out [here](https://github.com/giggls/opencampsitemap/issues/12#issuecomment-626789110):

> For referencing an external database we would need to invent an additional tag like we already have done for Wikidata.

Or, the other way around, Mangrove would provide us with an API that returns reviews for a place which is identified by its OSM ID.

Just my thoughts for now.

**Comment by giggls** [comment]
> Or, the other way around, Mangrove would provide us with an API that returns reviews for a place which is identified by its OSM ID.

This will not work because OSM-IDs are not a stable target.

E.g. if we have a campsite mapped as a node only and some Mapper with local knowledge will delete this node and draw a polygon instead.

**Comment by giggls** [comment]
I think I will merge this state for now. Objections?

**Comment by jonsger** [comment]
On 04.08.22 11:47, Sven Geggus wrote:
> Is there a way to find all reviewed sites on Mangrove?

https://api.mangrove.reviews/reviews gives you a CSV with all reviews
(about 500).

**Pull request merged**
