### PR TITLE
Updated translation to Russian and fixed some grammar

### PR DESCRIPTION
**Pull request by vmartyanov**

### CODE REVIEW

**Comment by giggls** [comment]
You will also need to update the html templates ``templates/index.ru.html`` and ``templates/noscript.ru.html``

**Comment by vmartyanov** [comment]
Seems they're mostly translated

**Comment by giggls** [comment]
No. index,ru,html has (at least): "Zoom in to display campsites!" and noscript.ru.html has "The map only works with javascript enabled."

**Comment by vmartyanov** [comment]
You're right. I'm not a web-dev, didn't see it without proper syntax highlight in other editor

**Comment by vmartyanov** [comment]
Yep, looks weird. I can try shorten the phrase, do you need it?

**Comment by giggls** [comment]
yes, would be nice.

**Pull request merged**
